module.exports = {
    black: '#000000',
    white: '#ffffff',
    salt: '#f8f8f8',
    magenta: '#CE003B',
    darkMagenta: '#b51135',
    lightGray: '#aaaaaa',
    darkGray: '#cccccc',
    lighterGray: '#f6f6f6',
    green: '#50d2c2',
    lightGreen: '#C7FA62',
    darkGreen: '#023203',
    blue: '#08bdce',
    orange: '#ffa809',
    brightBlue: '#007AFF',
    blueColor: '#006cff',
    transparent: 'transparent',
    lightestGray: '#DDDDDD',
    blueFbColor: '#3b5998',
    lightOrange: '#ff7200',
    pink: '#f6485d',
    swipeRowBackgroundColor: '#f9f9f9',
    swipeRowTextColor: '#707070',
    darkBrown: '#2f2f2f',
    orangeProfileCompletion: '#ff8400',
    quickRateBtnColor: '#188cf8',
    greyBlue: '#7DA5B3',
    greenGrey: '#9DA381',
    yellowOrange: '#FDB42B',
    redPink: '#FC6020',
    greyText: '#ABABAC',
    avatarBg: '#61A8B1',
    lightBlue: '#7ba3b2',
    brightGreen: '#c4fc56',
    blackishBrown: '#25292E',
    disabledBtnColor: '#eeeeee',
    progressBarColor: '#ff7e00',
    tabBottomBar: '#f97000',
    amazingOrange: '#ff6000',
    mehStone: '#9ca27e',
    awfulBlue: '#7ba3b2',
    goodOrange: '#ffb400',
  
    // Nuvasive
  
    appStatusBarColor : '#dadada',
    appPrimaryDarkColor: '#682566',
    appPrimaryLightColor : '#4b4b4b',
    appHeadingTextColor : '#4c4c4c',
    appHeaderColor : '#e1e1e1',
    appTabBackgroundColor : '#fafafa',
    appTabSelectedBackgroundColor : '#e5e5e5',
    appPrimaryBackgroundColor:'#fff',
    appPrimaryBorderColor : '#5a5a5a',
    appPrimaryIconColor : '#595959',
    appHeaderSecondaryColor : '#919292',
    appCarouselBackgroundColor : '#c3c3c3',
    appSearchResultColor : '#676767',
  
  
    appTabBackgroundColor : '#fafafa',
    appTabSelectedBackgroundColor : '#e5e5e5',
    appTabBorderColor : '#959595',
    appTabActiveTintColor : '#59595c',
    
  
  };
  